#!/usr/bin/php
<?php

assert_options(ASSERT_BAIL, true);
//
// pg - print all PG and PG-13 movies of a given year
//

// include the common PHP code file
require("a2.php");

/*
    GLOBAL VARIABLES
*/
$maxBaconNum = 6;

/*
    QUERIES
*/

// returns a query list of 'acting' roles related to an actor
/*
    function listRelations($actorId){
    $query = '
        select  %d as src,
                movie_id as rel,
                actor_id as dst
          from  listRelations(%d)
    ';
    return dbQuery($GLOBALS['db'], mkSQL($query, $actorId, $actorId));
    }*/

function listEdges($actorId, $graph){
    $movies = $graph['byActor'];
    $movies = $movies[$actorId];
    $edges = array();
    foreach($movies as $movie){
        $actors = $graph['byMovie'];
        $actors = $actors[$movie];
        foreach($actors as $actor){
            if($actor != $actorId){
                $edge['rel'] = $movie;
                $edge['dst'] = $actor;
                array_push($edges, $edge);
            }
        }
    }
    return $edges;
}
// Checks if vertex has already been visited in the path
function isNotVisited($vertex, $path){
    foreach ($path as $edge){
        if ($edge['dst'] == $vertex)
            return false;
    }
    return true;
}

function getAllRelations(){

    $query = "select movie_id, array_to_string(array_agg(actor_id),',') as actors from acting group by movie_id";
    $result = dbQuery($GLOBALS['db'], $query);
    $byMovie = array();
    while ($movie = dbNext($result)){
        $byMovie[$movie['movie_id']] = explode(',',$movie['actors']);
    }
    $query = "select actor_id, array_to_string(array_agg(movie_id),',') as movies from acting group by actor_id";
    $result = dbQuery($GLOBALS['db'], $query);
    $byActor = array();
    while ($actor = dbNext($result)){
        $byActor[$actor['actor_id']] = explode(',',$actor['movies']);
    }
    return $graph = array ('byMovie' => $byMovie, 'byActor' => $byActor);
}

/*
    $visited = (vertex => parent edge)
    visited stores the parent edge to the vertex
    vertices are actor ids
    edges are acting relation $edge = ('actor_id' => %d, 'movie_id' => %d)
*/
function shortestPaths($src, $dst){
    $graph = getAllRelations();
    $pathsToDestination = array();
    $queue = new SplQueue();         // A Queue of paths

    // Initialise queue with edges from src
    $edges = listEdges($src, $graph);
    foreach ($edges as $edge){
        $newPath = array();
        $edge['src'] = $src;
        $vertex = $edge['dst'];
        array_push($newPath, $edge);
        $queue->push($newPath);  // queue vertex for searching
    }

    while ($queue->count() > 0) {
        $path = $queue->pop();      // load the next vertex to search
        $lastEdge = end($path);
        $vertex = $lastEdge['dst'];

        $baconNum = count($path);

        // early exits
        if ($vertex == $dst && $baconNum <= $GLOBALS['maxBaconNum']){
            if ($baconNum < $GLOBALS['maxBaconNum']){
                $GLOBALS['maxBaconNum'] = $baconNum;
                echo "maxBaconNum updated to $baconNum\n";
            }
            echo "Path found of bacon number $baconNum\n";
            array_push($pathsToDestination, $path);
            continue;
        } else if ($baconNum + 1 > $GLOBALS['maxBaconNum']){
            continue;
        }

        $edges = listEdges($vertex, $graph);
        foreach ($edges as $edge){
           // If we find an relation that leads to the endActor
            if (isNotVisited($edge['dst'], $path)){
                $newPath = $path;
                $edge['src'] = $vertex;
                array_push($newPath, $edge);
                $queue->push($newPath);  // queue vertex for searching
            }
        }
    }
    return $pathsToDestination;
}

function printPaths($paths, $startActor){
    $lines = array();
    foreach ($paths as $path){
        $baconNum = count($path);
        if ($baconNum > $GLOBALS['maxBaconNum'])
            continue;
        $relations = array();
        // for each relation
        foreach ($path as $edge){
            $srcActor = getActor((int)$edge['src']);
            $movie    = getMovie((int)$edge['rel']);
            $actor    = getActor((int)$edge['dst']);
            $relation = "$srcActor[name] was in $movie[title]";
            if(!empty($movie['year']))
                $relation = $relation." ($movie[year])";
            $relation = $relation." with $actor[name]";
            // push relation
            array_push($relations, $relation);
        }
        $line = join('; ', $relations);
        array_push($lines, "$line");
    }
    natcasesort($lines);

    $i = 1;
    foreach ($lines as $line){
        echo "$i. $line\n";
        $i++;
    }
}


/*
    PROGRAM BODY BEGINS
*/
// Check arguments
$usage = "Usage: startActor endActor\n";
$usage = $usage."e.g \"tom cruise\" \"Jeremy Renner\"\n";

if (count($argv) < 2) exit("$usage\n");

// Find the starting actor's ID
$startActor = getActor($argv[1]);
if (!$startActor){
    echo "$argv[1] not found";
    return;
}
// Find the ending actor's ID
$endActor = getActor($argv[2]);
if (!$endActor){
    echo "$argv[2] not found";
    return;
}

// Find the shortest paths to the end actor
$paths = shortestPaths($startActor['id'], $endActor['id']);
printPaths($paths, $startActor);

echo "\n";


?>
